language: node_js

os:
  - linux
  - osx

dist: xenial
osx_image: xcode10.2

services:
  - xvfb

node_js:
  - '12'

cache:
  - npm
  - yarn

before_install:
  - yarn global add lerna

install:
  - travis_retry yarn bootstrap

script:
  - git diff --exit-code yarn.lock
  - CI=false yarn build
  - yarn test
