language: node_js

node_js:
  - '11.10'

cache:
  - npm
  - yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - travis_retry yarn install
  - travis_retry yarn lerna bootstrap

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - yarn build
  - yarn test
