language: node_js

addons:
  apt:
    packages:
      - xvfb

node_js:
  - '11.10'

cache:
  - npm
  - yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - travis_retry yarn install
  - travis_retry yarn lerna bootstrap

script:
  - yarn test
