language: node_js

os:
  - linux
  - osx

dist: xenial
osx_image: xcode10.2

services:
  - xvfb

node_js:
  - '11'
  - '12'

cache:
  - npm
  - yarn

before_install:
  # - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  # - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add lerna

install:
  - travis_retry yarn bootstrap

script:
  - git diff --exit-code yarn.lock
  - CI=false yarn build
  - yarn test
